global:
  scrape_interval:     15s
  external_labels:
    monitor: 'kaija-monitor'

rule_files:
  - /etc/prometheus/alert.rules
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  - job_name: 'node-exporter'
    scrape_interval: 5s
    target_groups:
      - targets: ['10.211.55.43:9100']
        labels:
          group: 'production'

  - job_name: 'push-gateway'
    scrape_interval: 5s

    target_groups:
      - targets: ['10.211.55.43:9091']
        labels:
          group: 'production'

  - job_name: 'nginx-exporter'
    scrape_interval: 5s

    target_groups:
      - targets: ['10.211.55.43:9113']
        labels:
          group: 'nginx'
